'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/app/components/ui/button';

// --- 1. IMPORT PDF LIBRARIES CORRECTLY ---
import jsPDF from 'jspdf';
// Use this require syntax for Next.js compatibility with autoTable
import autoTable from 'jspdf-autotable'; 

import ReportFilters from '@/app/components/reports/ReportFilters';
import ReportSummaryCards from '@/app/components/reports/ReportSummaryCards';
import ReportTable from '@/app/components/reports/ReportTable';
import ReportExport from '@/app/components/reports/ReportExport';

import {
  ScanLog,
  getAllScanLogs,
  getScanLogsByFactory,
} from '@/app/api/reports';

/* ---------------- TYPES ---------------- */

interface PatrolLocation {
  employee_name: string;
  employee_id: string;
  patrol_time: string;
  location: string;
  latitude: string;
  longitude: string;
}

interface PatrolRound {
  s_no: number;
  date: string;
  start_time: string;
  end_time: string;
  table: PatrolLocation[];
}

interface PatrolReportResponse {
  factory_name: string;
  factory_address: string;
  report_date: string;
  generated_by: string;
  generated_at: string;
  rounds: PatrolRound[];
}

/* ---------------- API HELPER ---------------- */

const getPatrolReport = async (
  factoryCode: string, 
  date: string
): Promise<PatrolReportResponse> => {
  const baseUrl = "http://127.0.0.1:8000"; 
  const params = new URLSearchParams({
    factory_code: factoryCode,
    date: date,
  });

  const response = await fetch(`${baseUrl}/api/report/patrol?${params.toString()}`, {
    method: "GET",
    headers: { "Content-Type": "application/json" },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to download report: ${response.statusText}. ${errorText}`);
  }

  return response.json();
};

/* ---------------- PDF GENERATION HELPER ---------------- */

// We pass factoryCode separately to avoid the type error with data.factory_code
const generatePDF = (data: PatrolReportResponse, factoryCode: string) => {
  const doc = new jsPDF();

  // --- 1. HEADER SECTION ---
  doc.setFontSize(18);
  doc.text("Patrol Report", 14, 22);

  doc.setFontSize(11);
  doc.setTextColor(100);
  
  // Factory Details
  doc.text(`Factory Name: ${data.factory_name}`, 14, 32);
  doc.text(`Address: ${data.factory_address}`, 14, 38);
  
  // Report Details
  const dateStr = new Date(data.report_date).toLocaleDateString();
  const generatedStr = new Date(data.generated_at).toLocaleString();
  
  doc.text(`Report Date: ${dateStr}`, 14, 46);
  doc.text(`Generated By: ${data.generated_by}`, 14, 52);
  doc.text(`Generated At: ${generatedStr}`, 14, 58);

  // --- 2. ROUNDS & SCANS LOOP ---
  let finalY = 68; // Starting Y position for the first table

  data.rounds.forEach((round) => {
    // Check if we need a new page
    if (finalY > 250) {
      doc.addPage();
      finalY = 20;
    }

    // Round Title
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`Round ${round.s_no}`, 14, finalY);
    
    // Round Subtitle (Times)
    doc.setFontSize(10);
    doc.setTextColor(100);
    
    // Helper to format time safely
    const formatTime = (timeStr: string) => {
        if(!timeStr) return 'N/A';
        try { return new Date(timeStr).toLocaleTimeString(); } 
        catch { return timeStr; }
    };

    doc.text(
      `From: ${formatTime(round.start_time)} To: ${formatTime(round.end_time)}`, 
      14, 
      finalY + 6
    );

    // Prepare Table Data
    const tableBody = round.table.map((scan) => [
      scan.employee_name,
      scan.employee_id,
      scan.location,
      new Date(scan.patrol_time).toLocaleTimeString(),
      `${scan.latitude}, ${scan.longitude}`,
    ]);

    // --- 3. DRAW TABLE ---
    // Use the imported autoTable function directly
    autoTable(doc, {
      startY: finalY + 10,
      head: [['Guard Name', 'Emp ID', 'Location', 'Time', 'Coords']],
      body: tableBody,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] }, // Blue header
      styles: { fontSize: 9 },
    });

    // Update finalY to the bottom of the table + 10 margin
    // We access lastAutoTable from the doc instance
    finalY = (doc as any).lastAutoTable.finalY + 10;
  });

  // --- 4. SAVE FILE ---
  // FIX: Use the factoryCode passed as argument, not data.factory_code
  const fileName = `Patrol_Report_${factoryCode}_${data.report_date}.pdf`;
  doc.save(fileName);
};

/* ---------------- PAGE COMPONENT ---------------- */

export default function ReportDownloadPage() {
  /* ---------- STATE ---------- */
  const [activeTab, setActiveTab] = useState<'scanCompliance' | 'guardPerformance'>('scanCompliance');
  const [reportPeriod, setReportPeriod] = useState<'daily' | 'weekly' | 'monthly' | 'yearly'>('daily');

  const [filters, setFilters] = useState({
    dateRange: { start: '', end: '' },
    site: '',
    route: '',
    guard: '',
  });

  const [logs, setLogs] = useState<ScanLog[]>([]);
  const [loading, setLoading] = useState(false);

  const [downloadingPatrol, setDownloadingPatrol] = useState(false);
  const [patrolError, setPatrolError] = useState<string | null>(null);

  /* ---------- FETCH LOGS ---------- */
  useEffect(() => {
    fetchLogs();
  }, [filters.site]);

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const data = filters.site
        ? await getScanLogsByFactory(filters.site)
        : await getAllScanLogs();
      setLogs(data);
    } catch (err) {
      console.error('Failed to fetch scan logs', err);
    } finally {
      setLoading(false);
    }
  };

  /* ---------- PATROL REPORT HANDLER (PDF) ---------- */

  const handleDownloadPatrolReport = async () => {
    if (!filters.site) {
      alert("Please select a Site (Factory) first.");
      return;
    }
    if (!filters.dateRange.start) {
      alert("Please select a Start Date for the report.");
      return;
    }

    setDownloadingPatrol(true);
    setPatrolError(null);

    try {
      // 1. Fetch Data
      const reportData = await getPatrolReport(filters.site, filters.dateRange.start);
      
      // 2. Generate and Save PDF (Passing filters.site to fix filename error)
      generatePDF(reportData, filters.site);
      
      alert("Patrol Report PDF downloaded successfully!");

    } catch (err) {
      console.error(err);
      const message = err instanceof Error ? err.message : "Unknown error";
      setPatrolError(message);
      alert(`Error: ${message}`);
    } finally {
      setDownloadingPatrol(false);
    }
  };

  /* ---------- TRANSFORM DATA ---------- */
  const scanComplianceData = useMemo(() => {
    return logs.map((log, index) => ({
      id: log.id ?? index,
      siteName: log.factory_code ?? 'N/A',
      routeName: log.qr_name ?? 'N/A',
      guardName: log.guard_name ?? 'N/A',
      missedScans: log.status === 'MISSED' ? 1 : 0,
      compliancePercentage: log.status === 'SUCCESS' ? 100 : 0,
    }));
  }, [logs]);

  const guardPerformanceData = useMemo(() => {
    const guardMap: Record<string, { missedScans: number; total: number; onTime: number }> = {};

    logs.forEach((log) => {
      const guard = log.guard_name ?? 'Unknown';
      if (!guardMap[guard]) {
        guardMap[guard] = { missedScans: 0, total: 0, onTime: 0 };
      }
      guardMap[guard].total += 1;
      if (log.status === 'MISSED') guardMap[guard].missedScans += 1;
      if (log.status === 'SUCCESS') guardMap[guard].onTime += 1;
    });

    return Object.entries(guardMap).map(([guardName, data], idx) => ({
      id: idx + 1,
      guardName,
      missedScans: data.missedScans,
      onTimeScanPercentage: data.total ? Math.round((data.onTime / data.total) * 100) : 0,
    }));
  }, [logs]);

  /* ---------------- UI ---------------- */

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">Reports</h1>
        <Button asChild variant="outline" size="sm">
          <Link href="/">Back to Dashboard</Link>
        </Button>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b pb-2 mb-6">
        <Button variant={activeTab === 'scanCompliance' ? 'default' : 'outline'} onClick={() => setActiveTab('scanCompliance')}>
          Scan Compliance Report
        </Button>
        <Button variant={activeTab === 'guardPerformance' ? 'default' : 'outline'} onClick={() => setActiveTab('guardPerformance')}>
          Guard Performance Report
        </Button>
      </div>

      {/* Filters & Download Button */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
        <div className="w-full md:w-auto">
          <ReportFilters filters={filters} setFilters={setFilters} />
        </div>

        <Button 
          onClick={handleDownloadPatrolReport} 
          disabled={downloadingPatrol}
          className="bg-red-600 hover:bg-red-700 text-white"
        >
          {downloadingPatrol ? "Generating PDF..." : "Download Patrol Report (PDF)"}
        </Button>
      </div>

      {patrolError && (
        <div className="mb-4 p-4 bg-red-100 text-red-700 rounded border border-red-300">
          {patrolError}
        </div>
      )}

      <div className="my-6">
        <ReportSummaryCards logs={logs as any} />
      </div>

      <div className="bg-white rounded-lg shadow p-4">
        <ReportTable logs={logs as any} loading={loading} />
      </div>

      <div className="flex justify-end mt-4">
        <ReportExport logs={logs as any} />
      </div>
    </div>
  );
}