'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/app/components/ui/button';

import ReportFilters from '@/app/components/reports/ReportFilters';
import ReportSummaryCards from '@/app/components/reports/ReportSummaryCards';
import ReportTable from '@/app/components/reports/ReportTable';
import ReportExport from '@/app/components/reports/ReportExport';

// IMPORT THE NEW COMPONENT
import PatrolReportPDF from '@/app/components/reports/PatrolReportPDF';

import {
  ScanLog,
  getAllScanLogs,
  getScanLogsByFactory,
} from '@/app/api/reports';

/* ---------------- TYPES ---------------- */

interface PatrolReportResponse {
  factory_name: string;
  factory_address: string;
  report_date: string;
  generated_by: string;
  generated_at: string;
  rounds: any[];
}

/* ---------------- API HELPER ---------------- */

const getPatrolReport = async (
  factoryCode: string, 
  date: string
): Promise<PatrolReportResponse> => {
  const baseUrl = "http://127.0.0.1:8000"; 
  const params = new URLSearchParams({
    factory_code: factoryCode,
    date: date,
  });

  const response = await fetch(`${baseUrl}/api/report/patrol?${params.toString()}`, {
    method: "GET",
    headers: { "Content-Type": "application/json" },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to download report: ${response.statusText}. ${errorText}`);
  }

  return response.json();
};

/* ---------------- PAGE COMPONENT ---------------- */

export default function ReportDownloadPage() {
  /* ---------- STATE ---------- */
  const [activeTab, setActiveTab] = useState<'scanCompliance' | 'guardPerformance'>('scanCompliance');
  const [reportPeriod, setReportPeriod] = useState<'daily' | 'weekly' | 'monthly' | 'yearly'>('daily');

  const [filters, setFilters] = useState({
    dateRange: { start: '', end: '' },
    site: '',
    route: '',
    guard: '',
  });

  const [logs, setLogs] = useState<ScanLog[]>([]);
  const [loading, setLoading] = useState(false);

  // NEW: State for Patrol Report Data
  const [patrolReportData, setPatrolReportData] = useState<PatrolReportResponse | null>(null);
  const [downloadingPatrol, setDownloadingPatrol] = useState(false);
  const [patrolError, setPatrolError] = useState<string | null>(null);

  /* ---------- FETCH LOGS ---------- */
  useEffect(() => {
    fetchLogs();
  }, [filters.site]);

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const data = filters.site
        ? await getScanLogsByFactory(filters.site)
        : await getAllScanLogs();
      setLogs(data);
    } catch (err) {
      console.error('Failed to fetch scan logs', err);
    } finally {
      setLoading(false);
    }
  };

  /* ---------- PATROL REPORT HANDLER ---------- */

  const handleFetchPatrolReport = async () => {
    if (!filters.site) {
      alert("Please select a Site (Factory) first.");
      return;
    }
    if (!filters.dateRange.start) {
      alert("Please select a Start Date for the report.");
      return;
    }

    setDownloadingPatrol(true);
    setPatrolError(null);

    try {
      // 1. Fetch Data
      const data = await getPatrolReport(filters.site, filters.dateRange.start);
      
      // 2. Set Data in State (So the component can generate PDF)
      setPatrolReportData(data);
      
      // Note: The PDF is generated by the component, not here.
      alert("Report data loaded! Click 'Generate & Download PDF' to download.");
      
    } catch (err) {
      console.error(err);
      const message = err instanceof Error ? err.message : "Unknown error";
      setPatrolError(message);
      alert(`Error: ${message}`);
    } finally {
      setDownloadingPatrol(false);
    }
  };

  /* ---------- TRANSFORM DATA ---------- */
  const scanComplianceData = useMemo(() => {
    return logs.map((log, index) => ({
      id: log.id ?? index,
      siteName: log.factory_code ?? 'N/A',
      routeName: log.qr_name ?? 'N/A',
      guardName: log.guard_name ?? 'N/A',
      missedScans: log.status === 'MISSED' ? 1 : 0,
      compliancePercentage: log.status === 'SUCCESS' ? 100 : 0,
    }));
  }, [logs]);

  const guardPerformanceData = useMemo(() => {
    const guardMap: Record<string, { missedScans: number; total: number; onTime: number }> = {};

    logs.forEach((log) => {
      const guard = log.guard_name ?? 'Unknown';
      if (!guardMap[guard]) {
        guardMap[guard] = { missedScans: 0, total: 0, onTime: 0 };
      }
      guardMap[guard].total += 1;
      if (log.status === 'MISSED') guardMap[guard].missedScans += 1;
      if (log.status === 'SUCCESS') guardMap[guard].onTime += 1;
    });

    return Object.entries(guardMap).map(([guardName, data], idx) => ({
      id: idx + 1,
      guardName,
      missedScans: data.missedScans,
      onTimeScanPercentage: data.total ? Math.round((data.onTime / data.total) * 100) : 0,
    }));
  }, [logs]);

  /* ---------------- UI ---------------- */

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">Reports</h1>
        <Button asChild variant="outline" size="sm">
          <Link href="/">Back to Dashboard</Link>
        </Button>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b pb-2 mb-6">
        <Button variant={activeTab === 'scanCompliance' ? 'default' : 'outline'} onClick={() => setActiveTab('scanCompliance')}>
          Scan Compliance Report
        </Button>
        <Button variant={activeTab === 'guardPerformance' ? 'default' : 'outline'} onClick={() => setActiveTab('guardPerformance')}>
          Guard Performance Report
        </Button>
      </div>

      {/* Filters & Fetch Button */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
        <div className="w-full md:w-auto">
          <ReportFilters filters={filters} setFilters={setFilters} />
        </div>

        <Button 
          onClick={handleFetchPatrolReport} 
          disabled={downloadingPatrol}
          className="bg-blue-600 hover:bg-blue-700 text-white"
        >
          {downloadingPatrol ? "Loading Report..." : "Load Patrol Report"}
        </Button>
      </div>

      {patrolError && (
        <div className="mb-4 p-4 bg-red-100 text-red-700 rounded border border-red-300">
          {patrolError}
        </div>
      )}

      {/* --- NEW: SHOW PATROL REPORT COMPONENT --- */}
      {patrolReportData && (
        <div className="bg-white rounded-lg shadow p-6 mb-6 border border-gray-200">
          <h2 className="text-lg font-bold mb-4">Patrol Report Ready</h2>
          <div className="grid grid-cols-2 gap-4 text-sm text-gray-600 mb-4">
            <div>Factory: <span className="font-bold text-black">{patrolReportData.factory_name}</span></div>
            <div>Date: <span className="font-bold text-black">{patrolReportData.report_date}</span></div>
          </div>
          
          {/* CALL THE COMPONENT HERE */}
          <div className="flex justify-center">
            <PatrolReportPDF reportData={patrolReportData} factoryCode={filters.site} />
          </div>
        </div>
      )}

      {/* Existing Tables */}
      <div className="my-6">
        <ReportSummaryCards logs={logs as any} />
      </div>

      <div className="bg-white rounded-lg shadow p-4">
        <ReportTable logs={logs as any} loading={loading} />
      </div>

      <div className="flex justify-end mt-4">
        <ReportExport logs={logs as any} />
      </div>
    </div>
  );
}