'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/app/components/ui/button';
import { FileDown, AlertTriangle, Search, ChevronLeft, ChevronRight } from 'lucide-react';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; 

// Import the components (assuming these exist based on your file)
import ReportTabs from '@/app/components/reports/ReportTabs';
import ReportFilters from '@/app/components/reports/ReportFilters'; 
import ReportSummaryCards from '@/app/components/reports/ReportSummaryCards';

import {
  ScanLog,
  getAllScanLogs,
  getScanLogsByFactory,
} from '@/app/api/reports';

/* ---------------- TYPES ---------------- */

interface PatrolLocation {
  employee_name: string;
  employee_id: string;
  patrol_time: string;
  location: string;
  latitude: string;
  longitude: string;
}

interface PatrolRound {
  s_no: number;
  date: string;
  start_time: string;
  end_time: string;
  table: PatrolLocation[];
}

interface PatrolReportResponse {
  factory_name: string;
  factory_address: string;
  report_date: string;
  generated_by: string;
  generated_at: string;
  rounds: PatrolRound[];
}

/* ---------------- API HELPER ---------------- */

const getPatrolReport = async (
  factoryCode: string, 
  date: string
): Promise<PatrolReportResponse> => {
  const baseUrl = "http://127.0.0.1:8000"; 
  const params = new URLSearchParams({
    factory_code: factoryCode,
    date: date,
  });

  const response = await fetch(`${baseUrl}/api/report/patrol?${params.toString()}`, {
    method: "GET",
    headers: { "Content-Type": "application/json" },
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to download report: ${response.statusText}. ${errorText}`);
  }

  return response.json();
};

/* ---------------- PDF GENERATION HELPER ---------------- */

const generatePDF = (data: PatrolReportResponse, factoryCode: string) => {
  const doc = new jsPDF();

  // --- 1. HEADER SECTION ---
  doc.setFontSize(18);
  doc.text("Patrol Report", 14, 22);

  doc.setFontSize(11);
  doc.setTextColor(100);
  
  // Factory Details
  doc.text(`Factory Name: ${data.factory_name}`, 14, 32);
  doc.text(`Address: ${data.factory_address}`, 14, 38);
  
  // Report Details
  const dateStr = new Date(data.report_date).toLocaleDateString();
  const generatedStr = new Date(data.generated_at).toLocaleString();
  
  doc.text(`Report Date: ${dateStr}`, 14, 46);
  doc.text(`Generated By: ${data.generated_by}`, 14, 52);
  doc.text(`Generated At: ${generatedStr}`, 14, 58);

  // --- 2. ROUNDS & SCANS LOOP ---
  let finalY = 68; // Starting Y position for the first table

  data.rounds.forEach((round) => {
    // Check if we need a new page
    if (finalY > 250) {
      doc.addPage();
      finalY = 20;
    }

    // Round Title
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(`Round ${round.s_no}`, 14, finalY);
    
    // Round Subtitle (Times)
    doc.setFontSize(10);
    doc.setTextColor(100);
    
    const formatTime = (timeStr: string) => {
        if(!timeStr) return 'N/A';
        try { return new Date(timeStr).toLocaleTimeString(); } 
        catch { return timeStr; }
    };

    doc.text(
      `From: ${formatTime(round.start_time)} To: ${formatTime(round.end_time)}`, 
      14, 
      finalY + 6
    );

    // Prepare Table Data
    const tableBody = round.table.map((scan) => [
      scan.employee_name,
      scan.employee_id,
      scan.location,
      new Date(scan.patrol_time).toLocaleTimeString(),
      `${scan.latitude}, ${scan.longitude}`,
    ]);

    // --- 3. DRAW TABLE ---
    autoTable(doc, {
      startY: finalY + 10,
      head: [['Guard Name', 'Emp ID', 'Location', 'Time', 'Coords']],
      body: tableBody,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] }, // Blue header
      styles: { fontSize: 9 },
    });

    // Update finalY to the bottom of the table + 10 margin
    finalY = (doc as any).lastAutoTable.finalY + 10;
  });

  // --- 4. SAVE FILE ---
  const fileName = `Patrol_Report_${factoryCode}_${data.report_date}.pdf`;
  doc.save(fileName);
};

/* ---------------- EMBEDDED REPORT TABLE ---------------- */

interface Column {
  key: keyof ScanLog
  label: string
}

const EmbeddedReportTable = ({ logs, loading }: { logs: ScanLog[], loading: boolean }) => {
  const [sortConfig, setSortConfig] = useState<{
    key: keyof ScanLog
    direction: 'asc' | 'desc'
  }>({
    key: 'scan_time',
    direction: 'desc'
  })

  const [currentPage, setCurrentPage] = useState(1)
  const rowsPerPage = 10

  const columns: Column[] = [
    { key: 'scan_time', label: 'Scan Time' },
    { key: 'factory_code', label: 'Factory' },
    { key: 'guard_name', label: 'Guard' },
    { key: 'qr_name', label: 'Scan Point' },
    { key: 'status', label: 'Status' },
  ]

  const handleSort = (key: keyof ScanLog) => {
    let direction: 'asc' | 'desc' = 'asc'
    if (sortConfig?.key === key) {
      if (sortConfig.direction === 'asc') {
        direction = 'desc'
      } else {
        direction = 'asc'
      }
    } else {
      direction = 'desc' 
    }
    setSortConfig({ key, direction })
  }

  const sortedData = useMemo(() => {
    if (!sortConfig) return logs

    return [...logs].sort((a, b) => {
      const aValue = a[sortConfig.key]
      const bValue = b[sortConfig.key]

      if (sortConfig.key === 'scan_time') {
        const dateA = new Date(aValue as string).getTime()
        const dateB = new Date(bValue as string).getTime()
        return sortConfig.direction === 'asc' ? dateA - dateB : dateB - dateA
      }

      if (!aValue || !bValue) return 0

      if (aValue < bValue) return sortConfig.direction === 'asc' ? -1 : 1
      if (aValue > bValue) return sortConfig.direction === 'asc' ? 1 : -1
      return 0
    })
  }, [logs, sortConfig])

  const indexOfLastRow = currentPage * rowsPerPage
  const indexOfFirstRow = indexOfLastRow - rowsPerPage
  const currentRows = sortedData.slice(indexOfFirstRow, indexOfLastRow)
  const totalPages = Math.ceil(sortedData.length / rowsPerPage)

  const renderCell = (row: ScanLog, key: keyof ScanLog) => {
    const value = row[key]

    if (key === 'scan_time' && value) {
      return new Date(value as string).toLocaleString()
    }

    if (key === 'status') {
      const color =
        value === 'SUCCESS'
          ? 'bg-green-100 text-green-800'
          : value === 'MISSED'
          ? 'bg-red-100 text-red-800'
          : 'bg-gray-100 text-gray-800'

      return (
        <span className={`px-2 py-1 rounded-full text-xs font-medium ${color}`}>
          {value ?? 'UNKNOWN'}
        </span>
      )
    }

    return value ?? '—'
  }

  if (loading) {
    return (
      <div className="text-center py-6 text-slate-500">
        Loading scan logs...
      </div>
    );
  }

  if (!logs.length) {
    return (
      <div className="text-center py-6 text-slate-500">
        No scan records found
      </div>
    );
  }

  return (
    <div className="overflow-x-auto rounded-lg border border-slate-200 shadow-sm">
      <table className="min-w-full divide-y divide-slate-200">
        <thead className="bg-slate-50">
          <tr>
            {columns.map((col) => {
              const isActive = sortConfig?.key === col.key
              return (
                <th
                  key={col.key}
                  onClick={() => handleSort(col.key)}
                  className={`px-6 py-3 text-left text-xs font-bold uppercase tracking-wider cursor-pointer select-none transition-colors ${
                    isActive ? 'bg-blue-100 text-blue-700' : 'text-slate-500 hover:bg-slate-100'
                  }`}
                >
                  <div className="flex items-center gap-1">
                    {col.label}
                    {isActive ? (
                      sortConfig.direction === 'asc' ? <ChevronLeft className="w-3 h-3" /> : <ChevronRight className="w-3 h-3" />
                    ) : (
                      <div className="w-3 h-3 opacity-30 flex flex-col justify-center gap-[1px]">
                         <div className="w-full h-[1px] bg-slate-400"></div>
                         <div className="w-full h-[1px] bg-slate-400"></div>
                      </div>
                    )}
                  </div>
                </th>
              )
            })}
          </tr>
        </thead>

        <tbody className="bg-white divide-y divide-slate-200">
          {currentRows.map((row) => (
            <tr key={row.id} className="hover:bg-slate-50 transition-colors">
              {columns.map((col) => (
                <td key={col.key} className="px-6 py-4 whitespace-nowrap text-sm text-slate-700">
                  {renderCell(row, col.key)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      {totalPages > 1 && (
        <div className="mt-4 flex justify-between items-center px-2">
          <button
            onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
            disabled={currentPage === 1}
            className="px-4 py-2 border rounded shadow-sm text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50"
          >
            Previous
          </button>

          <span className="text-sm font-medium text-slate-600">
            Page {currentPage} of {totalPages}
          </span>

          <button
            onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
            disabled={currentPage === totalPages}
            className="px-4 py-2 border rounded shadow-sm text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-50"
          >
            Next
          </button>
        </div>
      )}
    </div>
  )
}

/* ---------------- PAGE COMPONENT ---------------- */

export default function ReportDownloadPage() {
  /* ---------- STATE ---------- */
  const [activeTab, setActiveTab] = useState('scanCompliance');
  const [reportPeriod, setReportPeriod] = useState<'daily' | 'weekly' | 'monthly' | 'yearly'>('daily');

  const [filters, setFilters] = useState({
    dateRange: { start: '', end: '' },
    site: '',
    route: '', 
    guard: '',
  });

  const [logs, setLogs] = useState<ScanLog[]>([]);
  const [loading, setLoading] = useState(false);

  const [downloadingPatrol, setDownloadingPatrol] = useState(false);
  const [patrolError, setPatrolError] = useState<string | null>(null);

  /* ---------- FETCH LOGS ---------- */
  useEffect(() => {
    fetchLogs();
  }, [filters.site]);

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const data = filters.site
        ? await getScanLogsByFactory(filters.site)
        : await getAllScanLogs();
      setLogs(data);
    } catch (err) {
      console.error('Failed to fetch scan logs', err);
    } finally {
      setLoading(false);
    }
  };

  /* ---------- PATROL REPORT HANDLER (PDF) ---------- */

  const handleDownloadPatrolReport = async () => {
    if (!filters.site) {
      alert("Please select a Site (Factory) first.");
      return;
    }
    if (!filters.dateRange.start) {
      alert("Please select a Start Date for the report.");
      return;
    }

    setDownloadingPatrol(true);
    setPatrolError(null);

    try {
      const reportData = await getPatrolReport(filters.site, filters.dateRange.start);
      generatePDF(reportData, filters.site);
      alert("Patrol Report PDF downloaded successfully!");
    } catch (err) {
      console.error(err);
      const message = err instanceof Error ? err.message : "Unknown error";
      setPatrolError(message);
      alert(`Error: ${message}`);
    } finally {
      setDownloadingPatrol(false);
    }
  };

  /* ---------- TRANSFORM DATA ---------- */
  const scanComplianceData = useMemo(() => {
    return logs.map((log, index) => ({
      id: log.id ?? index,
      siteName: log.factory_code ?? 'N/A',
      routeName: log.qr_name ?? 'N/A',
      guardName: log.guard_name ?? 'N/A',
      missedScans: log.status === 'MISSED' ? 1 : 0,
      compliancePercentage: log.status === 'SUCCESS' ? 100 : 0,
    }));
  }, [logs]);

  /* ---------------- UI ---------------- */

  return (
    <>
      <style jsx global>{`
        @keyframes fadeInSlide {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .fade-in-slide {
          animation: fadeInSlide 0.5s ease-out forwards;
        }
      `}</style>

      <div className="min-h-screen bg-slate-50 font-sans selection:bg-blue-100 flex flex-col">
        
        {/* ================= PRO HEADER ================= */}
        <div className="bg-white border-b border-slate-200 shadow-sm sticky top-0 z-10">
          <div className="max-w-7xl mx-auto px-6 py-4">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
              
              {/* Breadcrumb / Title Area */}
              <div className="flex items-center gap-4 overflow-hidden">
                <div className="h-8 w-1 bg-gradient-to-b from-blue-600 to-blue-400 rounded-full"></div>
                <div>
                  <h1 className="text-2xl font-bold text-slate-900 tracking-tight leading-none">
                    Scan Compliance
                  </h1>
                  <p className="text-xs text-slate-500 font-medium uppercase tracking-wider mt-1">
                    Reports Dashboard
                  </p>
                </div>
              </div>

              {/* Actions */}
              <div className="flex items-center gap-3">
                <Link href="/" className="text-sm font-medium text-slate-500 hover:text-blue-600 transition-colors">
                  Back to Dashboard
                </Link>
              </div>
            </div>
          </div>
        </div>

        {/* ================= MAIN CONTENT ================= */}
        <div className="max-w-7xl mx-auto px-6 py-8 flex-grow">
          
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
            
            {/* --- LEFT COLUMN: FILTERS & ACTION --- */}
            <div className="lg:col-span-1 space-y-6">
              {/* 
                 CHANGED: Wrapped filters and download button in a single card 
                 to keep the action "near the filter tab".
              */}
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col h-full">
                
                {/* Filter Section */}
                <div className="p-6 flex-grow">
                  <div className="mb-4 pb-4 border-b border-slate-100">
                      <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider">Report Configuration</h3>
                  </div>
                  <ReportFilters 
                    filters={filters} 
                    setFilters={setFilters}
                  />
                </div>

                {/* Action Section (Download Button) */}
                <div className="p-6 bg-slate-50 border-t border-slate-200 fade-in-slide">
                  <Button 
                    onClick={handleDownloadPatrolReport} 
                    disabled={downloadingPatrol}
                    className="w-full group flex items-center justify-center gap-2 shadow-md hover:bg-slate-800 bg-slate-900 text-white px-6 py-3 rounded-xl transition-all duration-300"
                  >
                    {downloadingPatrol ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white/30 border-t-transparent rounded-full animate-spin"></div>
                        Generating...
                      </>
                    ) : (
                      <>
                        <FileDown className="w-4 h-4" />
                        Download PDF Report
                      </>
                    )}
                  </Button>
                  <p className="text-[10px] text-center text-slate-400 mt-2">
                      Requires Site and Start Date selection
                  </p>
                </div>
              </div>
            </div>

            {/* --- RIGHT COLUMN: DATA --- */}
            <div className="lg:col-span-2 space-y-6 flex flex-col">
              
              {/* Error Alert */}
              {patrolError && (
                <div className="p-4 bg-red-50 border border-red-200 text-red-700 rounded-xl flex items-center gap-3 shadow-sm fade-in-slide">
                  <AlertTriangle className="w-5 h-5 flex-shrink-0" />
                  <span className="text-sm font-medium">{patrolError}</span>
                </div>
              )}

              {/* Summary Cards */}
              {!loading && (
                <div className="fade-in-slide">
                  <ReportSummaryCards logs={logs as any} />
                </div>
              )}

              {/* Table Container */}
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex-grow">
                
                {loading ? (
                  <div className="p-12 flex flex-col items-center justify-center space-y-4">
                    <div className="w-10 h-10 border-4 border-slate-200 border-t-blue-600 rounded-full animate-spin"></div>
                    <p className="text-slate-500 font-medium">Loading scan logs...</p>
                  </div>
                ) : logs.length === 0 ? (
                  <div className="p-12 text-center flex flex-col items-center justify-center h-64">
                    <div className="bg-slate-50 p-4 rounded-full mb-4">
                      <Search className="w-8 h-8 text-slate-400" />
                    </div>
                    <h3 className="text-lg font-medium text-slate-900">No Data Found</h3>
                    <p className="text-slate-500 text-sm mt-2">
                      Adjust your filters or select a different date range.
                    </p>
                  </div>
                ) : (
                  <div className="fade-in-slide">
                    <EmbeddedReportTable logs={logs} loading={loading} />
                  </div>
                )}
              </div>

            </div>
          </div>
        </div>
      </div>
    </>
  );
}