'use client';
import React, { useEffect } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// --- INTERFACES ---

interface PatrolLocation {
  employee_name?: string;
  employee_id?: string;
  patrol_time?: string;
  location?: string;
  latitude?: string;
  longitude?: string;
  start_time?: string;
  end_time?: string;
}

interface PatrolRound {
  s_no: number;
  date: string;
  start_time: string;
  end_time: string;
  time_range_display: string;
  status: string;
  table?: PatrolLocation[];
}

interface PatrolReportResponse {
  factory_name: string;
  factory_address: string;
  report_date: string;
  generated_by: string;
  generated_at: string;
  rounds: PatrolRound[];
}

// --- COMPONENT ---

interface PatrolReportPDFProps {
  reportData: PatrolReportResponse;
  factoryCode: string;
}

const PatrolReportPDF: React.FC<PatrolReportPDFProps> = ({ reportData, factoryCode }) => {

  useEffect(() => {
    if (!reportData) return;
    handleGeneratePDF();
  }, [reportData]);

  /**
   * FORCE CURRENT TIME
   * Ignores server input and returns the exact time right now on your device.
   */
  const getCurrentLocalTime = (): string => {
    const now = new Date(); // Gets current moment from your device
    
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    
    const hours = String(now.getHours()).padStart(2, '0');
    const minutes = String(now.getMinutes()).padStart(2, '0');
    const seconds = String(now.getSeconds()).padStart(2, '0');

    return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  };

  const handleGeneratePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // --- 1. HEADER SECTION ---
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Patrol Report", pageWidth / 2, 22, { align: "center" });

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);

    doc.text(`Factory Name: ${reportData.factory_name}`, pageWidth / 2, 28, { align: "center" });
    doc.text(`Address: ${reportData.factory_address}`, pageWidth / 2, 34, { align: "center" });

    const dateStr = new Date(reportData.report_date).toLocaleDateString();
    
    // --- 2. GET EXACT CURRENT TIME ---
    // We are NOT using reportData.generated_at anymore.
    const generatedStr = getCurrentLocalTime();

    doc.text(`Report Date: ${dateStr}`, pageWidth / 2, 40, { align: "center" });
    doc.text(`Generated By: ${reportData.generated_by}`, pageWidth / 2, 46, { align: "center" });
    doc.text(`Generated At: ${generatedStr}`, pageWidth / 2, 52, { align: "center" });

    // --- 3. ROUNDS LOOP ---
    let finalY = 58;

    reportData.rounds.forEach((round) => {
      if (finalY > 250) {
        doc.addPage();
        finalY = 20;
      }

      // Round Header
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0);
      doc.text(`Round ${round.s_no}`, 14, finalY);

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);

      const timeRangeText = round.time_range_display || "N/A";
      doc.text(`Time: ${timeRangeText}`, 14, finalY + 5);

      // --- 4. PREPARE TABLE DATA ---
      let tableBody: any[] = [];

      if (round.status === "SUCCESS" && round.table && round.table.length > 0) {
        tableBody = round.table.map((scan) => [
          scan.employee_name || "N/A",
          scan.location || "N/A",
          scan.patrol_time || "N/A",
          scan.latitude || "N/A",
          scan.longitude || "N/A",
          round.date || "N/A",
          "SUCCESS"
        ]);
      } else {
        tableBody.push([
          "-",
          "-",
          timeRangeText,
          "-",
          "-",
          timeRangeText,
          "MISSED"
        ]);
      }

      // --- 5. DRAW TABLE ---
      autoTable(doc, {
        startY: finalY + 10,
        head: [['Guard Name', 'Location', 'Time', 'Latitude', 'Longitude', 'Date', 'Status']],
        body: tableBody,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] },
        styles: { fontSize: 8 },
        didParseCell: (data) => {
          if (data.section === 'body') {
            if (data.column.index === data.table.columns.length - 1) {
              const cellContent = data.cell.raw;

              if (cellContent === "SUCCESS") {
                data.cell.styles.textColor = [0, 128, 0];
                data.cell.styles.fontStyle = 'bold';
              } else if (cellContent === "MISSED") {
                data.cell.styles.textColor = [220, 20, 60];
                data.cell.styles.fontStyle = 'bold';
              }
            }
          }
        },
      });

      finalY = (doc as any).lastAutoTable.finalY + 8;
    });

    // --- 6. SAVE FILE ---
    const fileName = `Patrol_Report_${factoryCode}_${reportData.report_date}.pdf`;
    doc.save(fileName);
  };

  return null;
};

export default PatrolReportPDF;