'use client';
import React, { useEffect, useState } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ROUND_TIMES, RoundTime } from "./roundtime"; 
import axios from 'axios';

// --- INTERFACES ---
export interface ScanLog {
  id: string | number;
  scan_time: string;
  factory_code: string;
  guard_name: string;
  qr_name: string;
  round: number;
  lat?: string;
  lon?: string;
  status: "SUCCESS" | "MISSED" | string;
  [key: string]: any;
}

interface PatrolReportPDFProps {
  logs: ScanLog[];
  factoryCode: string;
  factoryName: string;
  factoryAddress?: string; // optional, can be fetched
  reportDate: string;
  generatedBy: string;
}

const PatrolReportPDF: React.FC<PatrolReportPDFProps> = ({
  logs,
  factoryCode,
  factoryName,
  factoryAddress: initialAddress,
  reportDate,
  generatedBy
}) => {
  const [factoryAddress, setFactoryAddress] = useState<string>(initialAddress || '');

  // Fetch factory address if not provided
  useEffect(() => {
    if (!factoryAddress && factoryCode) {
      const fetchAddress = async () => {
        try {
          const res = await axios.get(`/api/factories/${factoryCode}`);
          const address = res.data.address || 'N/A';
          setFactoryAddress(address);
        } catch (err) {
          console.error("Failed to fetch factory address", err);
          setFactoryAddress('N/A');
        }
      };
      fetchAddress();
    }
  }, [factoryCode, factoryAddress]);

  useEffect(() => {
    if (!logs || logs.length === 0) return;
    handleGeneratePDF();
  }, [logs, factoryAddress]);

  const getFormattedDate = (dateString: string): string => {
    if (!dateString) return "N/A";
    try {
      const d = new Date(dateString);
      return d.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
    } catch {
      return dateString;
    }
  };

  const formatTime = (t?: string): string => {
    if (!t) return "N/A";
    try {
      return new Date(t).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    } catch {
      return "N/A";
    }
  };

  const handleGeneratePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const borderMargin = 12; 
    const leftMargin = 16;  

    const drawPageBorder = () => {
      doc.setDrawColor(50, 50, 50);
      doc.setLineWidth(0.5);
      doc.rect(borderMargin, borderMargin, pageWidth - (borderMargin * 2), pageHeight - (borderMargin * 2), 'S');
    };

    const THEME_GREEN: [number, number, number] = [6, 123, 69];
    const THEME_RED: [number, number, number] = [200, 50, 50];
    const THEME_BLUE: [number, number, number] = [0, 0, 139];

    // Filter logs
    const validLogs = logs.filter((log) => log.round !== 35);

    const logsByRound: Record<number, ScanLog[]> = {};
    validLogs.forEach((log) => {
      const r = log.round || 1;
      if (!logsByRound[r]) logsByRound[r] = [];
      logsByRound[r].push(log);
    });

    const sortedRoundKeys = Object.keys(logsByRound).map(Number).sort((a, b) => a - b);

    drawPageBorder();

    // HEADER
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageWidth, 48, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Security Patrol Report", pageWidth / 2, 20, { align: "center" });
    doc.setTextColor(...THEME_RED);
    doc.setFontSize(10);
    doc.text(factoryName.toUpperCase(), pageWidth / 2, 27, { align: "center" });
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(factoryAddress || "N/A", pageWidth / 2, 33, { align: "center" });

    // META INFO
    const colLeftX = leftMargin;
    const colRightX = 105;
    const headerInfoStartY = 40;
    const lineHeight = 5.5;
    const displayDate = getFormattedDate(reportDate);
    const generatedStr = formatTime(new Date().toISOString());

    const drawHeaderMeta = (label: string, value: string, yPos: number, xPos: number) => {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...THEME_BLUE);
      doc.text(`${label}:`, xPos, yPos);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...THEME_BLUE);
      doc.text(value, xPos + 25, yPos);
    };

    drawHeaderMeta("Factory", factoryName, headerInfoStartY, colLeftX);
    drawHeaderMeta("Date", displayDate, headerInfoStartY, colRightX);
    drawHeaderMeta("Generated By", generatedBy, headerInfoStartY + lineHeight, colLeftX);
    drawHeaderMeta("Generated At", generatedStr, headerInfoStartY + lineHeight, colRightX);

    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.5);
    doc.line(leftMargin, 52, pageWidth - leftMargin, 52);

    let finalY = 57;

    // ROUNDS LOOP
    sortedRoundKeys.forEach((roundNumber) => {
      if (finalY > 230) { 
        doc.addPage();
        drawPageBorder();
        finalY = borderMargin + 10;
      }

      const roundLogs = logsByRound[roundNumber];
      const roundTime: RoundTime | undefined = ROUND_TIMES[roundNumber];
      const startTime = roundTime?.start ?? "-";
      const endTime = roundTime?.end ?? "-";

      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(`Round ${roundNumber}  |  Start: ${startTime}, End: ${endTime}`, leftMargin, finalY + 7);

      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.5);
      doc.line(leftMargin, finalY + 10, pageWidth - leftMargin, finalY + 10);
      finalY += 16;

      const tableBody = roundLogs.length > 0
        ? roundLogs.map((log) => [
            formatTime(log.scan_time),
            log.factory_code || "N/A",
            log.guard_name || "N/A",
            log.qr_name || "N/A",
            log.lat || "0.0",
            log.lon || "0.0",
            log.status || "UNKNOWN"
          ])
        : [["-", "-", "-", "-", "-", "-", "NO DATA"]];

      autoTable(doc, {
        startY: finalY,
        head: [['Time', 'Factory', 'Guard Name', 'Scan Point', 'Latitude', 'Longitude', 'Status']],
        body: tableBody,
        theme: 'plain',
        headStyles: { fillColor: THEME_BLUE, textColor: 255, fontStyle: 'bold', fontSize: 9, halign: 'left' },
        styles: { fontSize: 8, cellPadding: 3, lineColor: [230,230,230], lineWidth: { top:0, right:0, bottom:0.2, left:0 } },
        alternateRowStyles: { fillColor: [250,253,250] },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 6) {
            const cellContent = String(data.cell.raw);
            if (cellContent.includes("SUCCESS")) { data.cell.styles.textColor = THEME_GREEN; data.cell.styles.fontStyle='bold'; }
            else if (cellContent.includes("MISSED")) { data.cell.styles.textColor = THEME_RED; data.cell.styles.fontStyle='bold'; }
          }
        }
      });

      finalY = (doc as any).lastAutoTable.finalY + 15;
    });

    // FOOTER
    const pageCount = doc.internal.pages.length - 1;
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount} - Generated by Security Verifier`, pageWidth / 2, pageHeight - 10, { align: "center" });
    }

    const fileName = `Patrol_Report_${factoryCode}_${reportDate}.pdf`;
    doc.save(fileName);
  };

  return null;
};

export default PatrolReportPDF;
